use_frameworks!

platform :ios, '9.0'

target 'Downloader_Example' do
  pod 'Downloader', :path => '../'

  target 'Downloader_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
